version: '3'

services:
  terraform:
    image: hashicorp/terraform:latest
    container_name: terraform_env
    volumes:
      - ./infrastructure:/workspace
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
    working_dir: "/workspace/service"

  elixir:
    image: erintheblack/elixir-lambda-builder:al2_1.10.4
    volumes:
      - ./infrastructure/functions:/buildroot
    environment:
      - MIX_ENV=prod
    working_dir: "/buildroot"
